//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Jurnal_Ucheta = new HashSet<Jurnal_Ucheta>();
        }
    
        public int Код_клиента { get; set; }
        public string Наименование_предприятия { get; set; }
        public Nullable<int> Код_района { get; set; }
        public string Адрес { get; set; }
        public string ФИО { get; set; }
        public Nullable<decimal> Телефон { get; set; }
        public string Должность { get; set; }
        public Nullable<int> Код_плательщика { get; set; }
    
        public virtual Raion Raion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal_Ucheta> Jurnal_Ucheta { get; set; }
    }
}
