//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jurnal_Ucheta
    {
        public int Код_записи { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public Nullable<System.DateTime> Дата_подписания { get; set; }
        public Nullable<int> Номер_договора { get; set; }
        public Nullable<int> Комер_акта_накладной_ { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<int> Код_плательщика { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual VidUslug VidUslug { get; set; }
    }
}
