//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudniki()
        {
            this.Jurnal_Ucheta = new HashSet<Jurnal_Ucheta>();
        }
    
        public int КодCотрудника { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public Nullable<decimal> Телефон { get; set; }
        public string Адрес { get; set; }
        public string Документ { get; set; }
        public Nullable<decimal> Серия_Номер { get; set; }
        public string Семейное_положение { get; set; }
        public string Квалификация { get; set; }
        public Nullable<int> Код_специальности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal_Ucheta> Jurnal_Ucheta { get; set; }
        public virtual Special Special { get; set; }
    }
}
