//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kr
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidUslug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VidUslug()
        {
            this.Jurnal_Ucheta = new HashSet<Jurnal_Ucheta>();
        }
    
        public int Код_услуги { get; set; }
        public string Наименование_услуги { get; set; }
        public Nullable<int> Код_группы { get; set; }
        public string Единица_измерения { get; set; }
        public string Объем_работ { get; set; }
        public Nullable<decimal> Базовая_стоимость { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal_Ucheta> Jurnal_Ucheta { get; set; }
    }
}
